global:
  jenkinsAgent: any


ansible:
  stageName: Ansible
  dir: /var/lib/jenkins/workspace/pipe/Ansible
  cmd: ansible-playbook -i Inventory/${var.env}
  playbookDir: playbook
  playbookList:
    -
    - verify-connection.yml

  PreTask:
  PostTask:
